apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: llm-demo
spec:
  type: NodePort  # Use LoadBalancer if you're on a cloud that supports it
  selector:
    app: rag
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      # If using NodePort, you can optionally specify the nodePort:
      # nodePort: 30000